### ISSUE TITLE
Path in .gdbinit needs modification

### ISSUE THREAD

**Issue by tkittel** [daskol/gdb-colour-filter#6]
Hi there, thanks a lot for a very nice utility!

My gdb (Ubuntu 18.04) could not find the script with the .gdbinit source line proposed on the main page, instead I needed to add the tilde:

```
source ~/.gdb/gdb-colour-filter/colour_filter.py
```

Cheers,
Thomas

**Comment by daskol** [comment]
Thank you for your remark. I've updated README in PR #7.
